[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''love.graphics.setShader( G.SHADERS['CRT'])'''
position = "at"
payload = '''
if not G.override_crt then
    love.graphics.setShader( G.SHADERS['CRT'])
else
    
end
'''
match_indent = true